Name : Layan Alamri

# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
s1 = pd.Series(np.random.randint(1, 5, 100))
s2 = pd.Series(np.random.randint(1, 4, 100))
s3 = pd.Series(np.random.randint(10000, 30001, 100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [3]:
house = pd.concat([s1, s2, s3], axis=1)
house

    0  1      2
0   4  2  25953
1   2  3  28161
2   3  2  16387
3   3  2  11946
4   3  1  15141
.. .. ..    ...
95  2  1  22371
96  4  1  18257
97  2  3  13885
98  3  2  18447
99  4  3  29193

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [ ]:
house.columns = ["bedrs", "bathrs", "price_sqr_meter"]
house.head()

   bedrs  bathrs  price_sqr_meter
0      4       2            25953
1      2       3            28161
2      3       2            16387
3      3       2            11946
4      3       1            15141

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [6]:
bigcolumn = pd.DataFrame(pd.concat([s1, s2, s3], axis=0))
bigcolumn

        0
0       4
1       2
2       3
3       3
4       3
..    ...
95  22371
96  18257
97  13885
98  18447
99  29193

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [10]:
bigcolumn.index

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=300)

No, it is not true. The index is not only until 99. It has 300 values, but the indices from 0 to 99 are repeated three times.

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [11]:
bigcolumn = bigcolumn.reset_index(drop=True)
bigcolumn

         0
0        4
1        2
2        3
3        3
4        3
..     ...
295  22371
296  18257
297  13885
298  18447
299  29193

[300 rows x 1 columns]